/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectorForNominalCreatorPanel.java
 *
 * Created on 2009-04-29, 17:00:08
 */

package apw.temp_nitric.smieci;

import apw.temp_nitric.gui.*;
import apw.temp_nitric.controls.NominalValuesChooser;
import apw.temp_nitric.logic.Selector;
import apw.temp_nitric.logic.SelectorForNominal;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Nitric
 */
public class SelectorForNominalCreatorPanel extends SelectorCreatorPanel {
    private String attributesName = "Nieznana nazwa";
    private int attributesNumber;
    private int amountOfAllValues;
    private HashSet<String> values;
    private HashSet<String> allowedValues;
    private ComplexCreatorFrame parentFrame;
    
    public SelectorForNominalCreatorPanel(
            int attrId, String attrName, HashSet<String> values, ComplexCreatorFrame parent
            ) {
        this.attributesNumber = attrId;
        this.attributesName = attrName;
        this.values = values;
        this.allowedValues = values;
        this.parentFrame = parent;
        amountOfAllValues = values.size();
        initComponents();
    }

    public Selector getSelector() {
        if (allowedValues.size() == amountOfAllValues)
            return SelectorForNominal.getSelUniversal(attributesNumber);
        else
            return SelectorForNominal.getSelSet(attributesNumber, false, allowedValues);
    }

    public SelectorForNominalCreatorPanel() {
        initComponents();
    }

    public HashSet<String> getAllowedValues() {
        return allowedValues;
    }

    public void setAllowedValues(HashSet<String> allowedValues) {
        this.allowedValues = allowedValues;
        NominalComboBoxModel2 cbm = new NominalComboBoxModel2();
        cbm.setData(allowedValues);
        jcb_values.setModel(cbm);
    }

    public String getAttributesName() {
        return attributesName;
    }

    public void setAttributesName(String attributesName) {
        this.attributesName = attributesName;
    }

    public int getAttributesNumber() {
        return attributesNumber;
    }

    public void setAttributesNumber(int attributesNumber) {
        this.attributesNumber = attributesNumber;
    }

    public HashSet<String> getValues() {
        return values;
    }

    public void setValues(HashSet<String> values) {
        this.values = values;
        amountOfAllValues = values.size();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_name = new javax.swing.JLabel();
        jcb_values = new javax.swing.JComboBox(values.toArray());
        jb_modify = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(686, 30));

        jl_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_name.setText(attributesName);

        jb_modify.setText("Modyfikuj listę");
        jb_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_values, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcb_values, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jb_modify)
                .addComponent(jl_name, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modifyActionPerformed
        new NominalValuesChooser(parentFrame, null, values, attributesName).setVisible(true);
    }//GEN-LAST:event_jb_modifyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_modify;
    private javax.swing.JComboBox jcb_values;
    private javax.swing.JLabel jl_name;
    // End of variables declaration//GEN-END:variables

}

class NominalComboBoxModel2 implements ComboBoxModel {
    private ArrayList<String> data;
    private int selected;

    public void setData(HashSet<String> data) {
        this.data = new ArrayList<String>();
        this.data.addAll(data);
    }

    public void setSelectedItem(Object anItem) {
        selected = data.indexOf(anItem);
    }

    public Object getSelectedItem() {
        return data.get(selected);
    }

    public int getSize() {
        return data.size();
    }

    public Object getElementAt(int index) {
        return data.get(index);
    }

    public void addListDataListener(ListDataListener l) { }

    public void removeListDataListener(ListDataListener l) { }
}
