/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Okno2.java
 *
 * Created on 2009-04-26, 00:31:13
 */

package apw.temp_nitric.gui;

import apw.temp_nitric.logic.LoadingSamplesMain;
import apw.temp_nitric.logic.DataFile;

/**
 *
 * @author Nitric
 */
public class LoadingSamples_Step1 extends javax.swing.JFrame {

    private LoadingSamplesMain advisor;
    
    public LoadingSamples_Step1(LoadingSamplesMain advisor) {
        this.advisor = advisor;
        initComponents();
        setLocationRelativeTo(null);
        panel.setParent(this);
    }

    public void next(DataFile dataFile) {
        advisor.step2(dataFile);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new apw.temp_nitric.gui.FileChoosingAndFormatDeterminingPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingSamples_Step1(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apw.temp_nitric.gui.FileChoosingAndFormatDeterminingPanel panel;
    // End of variables declaration//GEN-END:variables

}
