/*
 * PrototypesFrame.java
 *
 * Created on 2009-08-06, 13:29:16
 */

package apw.art2a.gui;

import apw.core.Samples;
import apw.core.loader.ARFFLoader;
import apw.art2a.ART2A_Util;
import apw.art2a.Instance;
import apw.art2a.Network;
import apw.art2a.Prototype;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static apw.art2a.ART2A_Util.*;

/**
 *
 * @author nitric
 */
public class PrototypesFrame extends javax.swing.JFrame {

    private Network net;

    /** Creates new form PrototypesFrame */
    public PrototypesFrame(Network net) {
        this.net = net;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private static boolean labeled;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prototypesPanel1 = new apw.art2a.gui.PrototypesPanel(net);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prototypesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prototypesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apw.art2a.gui.PrototypesPanel prototypesPanel1;
    // End of variables declaration//GEN-END:variables
}
