/*
 * ConflictsResolvingPanel.java
 *
 * Created on 2009-05-28, 21:28:59
 */

package apw.augmentedLearning.gui;

import apw.core.Attribute;
import apw.core.Samples;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Nitric
 */
public class ConflictsResolvingPanel extends javax.swing.JPanel {
    private String[] categories;
    private ConflictsResolvingFrame parent;

    public String[] getCategories() {
        return categories;
    }

    public void setCategories(String[] categories) {
        this.categories = categories;
    }

    /** Creates new form ConflictsResolvingPanel */
    public ConflictsResolvingPanel() {
        categories = new String[] {"Raz", "Dwa"};
        initComponents();
    }

    //////////////////////////////////////////////////////////////////////////////////////

    public JButton getJb_ok() {
        return jb_ok;
    }

    public void setJb_ok(JButton jb_ok) {
        this.jb_ok = jb_ok;
    }

    public JComboBox getJcb_category() {
        return jcb_category;
    }

    public void setJcb_category(JComboBox jcb_category) {
        this.jcb_category = jcb_category;
    }

    public JLabel getJl_category() {
        return jl_category;
    }

    public void setJl_category(JLabel jl_category) {
        this.jl_category = jl_category;
    }

    public JLabel getJl_title() {
        return jl_title;
    }

    public void setJl_title(JLabel jl_title) {
        this.jl_title = jl_title;
    }

    public JScrollPane getJsp_scrollPane() {
        return jsp_scrollPane;
    }

    public void setJsp_scrollPane(JScrollPane jsp_scrollPane) {
        this.jsp_scrollPane = jsp_scrollPane;
    }

    public JTextArea getJt_sample() {
        return jt_sample;
    }

    public void setJt_sample(JTextArea jt_sample) {
        this.jt_sample = jt_sample;
    }

    //////////////////////////////////////////////////////////////////////////////////////
    
    public ConflictsResolvingPanel(
            Object[] sample,
            String[] categories,
            Samples samples,
            int classAttId,
            ConflictsResolvingFrame parent
            ) {
        this.categories = categories;
        this.parent = parent;
        initComponents();
        prepareData(sample, samples, classAttId);
    }

    private void prepareData(Object[] sample, Samples samples, int classAttId) {
        ArrayList<Attribute> atts = samples.getAtts();
        for (int i = 0; i < sample.length; i++) {
            if (i == classAttId)
                continue;
            jt_sample.append(atts.get(i).getName() + " = " + sample[i] + "\n");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_title = new javax.swing.JLabel();
        jsp_scrollPane = new javax.swing.JScrollPane();
        jt_sample = new javax.swing.JTextArea();
        jl_category = new javax.swing.JLabel();
        jcb_category = new javax.swing.JComboBox();
        jb_ok = new javax.swing.JButton();

        jl_title.setFont(new java.awt.Font("Tahoma", 1, 12));
        jl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title.setText("Proszę wskazać kategorię dla poniższego przykładu:");

        jt_sample.setColumns(20);
        jt_sample.setRows(5);
        jsp_scrollPane.setViewportView(jt_sample);

        jl_category.setText("Poprawna kategoria:");

        jcb_category.setModel(new javax.swing.DefaultComboBoxModel(categories));

        jb_ok.setText("OK");
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp_scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_category)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_category, 0, 169, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_ok)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_category)
                    .addComponent(jcb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ok))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
        parent.valueChosen((String) jcb_category.getSelectedItem());
    }//GEN-LAST:event_jb_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_ok;
    private javax.swing.JComboBox jcb_category;
    private javax.swing.JLabel jl_category;
    private javax.swing.JLabel jl_title;
    private javax.swing.JScrollPane jsp_scrollPane;
    private javax.swing.JTextArea jt_sample;
    // End of variables declaration//GEN-END:variables

}
