package apw.augmentedLearning.gui;

import apw.core.Samples;


/*
 * ConflictsResolvingFrame.java
 *
 * Created on 2009-05-28, 21:53:58
 */

/**
 *
 * @author Nitric
 */
public class ConflictsResolvingFrame extends javax.swing.JFrame {
    private Object[] sample;
    private String[] categories;
    private Samples samples;
    private int classAttId;
    private LoadingSamples_Step2 parent;

    /** Creates new form ConflictsResolvingFrame */
    public ConflictsResolvingFrame() {
        initComponents();
    }

    public ConflictsResolvingFrame(
            Object[] sample,
            String[] categories,
            Samples samples,
            int classAttId,
            LoadingSamples_Step2 parent
            ) {
        this.sample = sample;
        this.categories = categories;
        this.samples = samples;
        this.classAttId = classAttId;
        this.parent = parent;
        new Thread() {
            @Override
            public void run() {
                initComponents();
                setLocationRelativeTo(null);
            }
        }.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conflictsResolvingPanel = new apw.augmentedLearning.gui.ConflictsResolvingPanel(sample, categories, samples, classAttId, this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Znaleziono sprzeczne przykłady");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conflictsResolvingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conflictsResolvingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void valueChosen(String s) {
        parent.setValue(s);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apw.augmentedLearning.gui.ConflictsResolvingPanel conflictsResolvingPanel;
    // End of variables declaration//GEN-END:variables

}
