/*
 * MissclassificationInfoFrame.java
 *
 * Created on 2009-05-23, 20:23:44
 */

package apw.augmentedLearning.gui;

/**
 *
 * @author Nitric
 */
public class MissclassificationInfoFrame extends javax.swing.JFrame {
    private LoadingSamples_Step3 parent = null;
    private int missclassifiedCount;

    /** Creates new form MissclassificationInfoFrame */
    public MissclassificationInfoFrame() {
        initComponents();
    }

    public MissclassificationInfoFrame(LoadingSamples_Step3 parent, int count) {
        this.parent = parent;
        missclassifiedCount = count;
        initComponents();
        setLocationRelativeTo(parent);
    }

    void action(int action) {
        dispose();
        parent.action(action);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new apw.augmentedLearning.gui.MissclassificationInfo(this, missclassifiedCount);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MissclassificationInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apw.augmentedLearning.gui.MissclassificationInfo infoPanel;
    // End of variables declaration//GEN-END:variables

}
