/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Srr.java
 *
 * Created on 2009-05-04, 18:49:22
 */

package apw.augmentedLearning.controls;

import java.util.HashSet;
import java.util.Iterator;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JCheckBox;

/**
 *
 * @author Nitric
 */
public class NominalValuesChooserPanel extends javax.swing.JPanel {

    private int amount = 15;
    private HashSet<String> set;
    private JCheckBox[] checkboxes;

    public void setAllCheckboxes(boolean b) {
        for (JCheckBox cb : checkboxes)
            cb.setSelected(b);
    }

    /** Creates new form Srr */
    public NominalValuesChooserPanel() {
        initComponents();
        // myInitComponents();
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public HashSet<String> getSet() {
        return set;
    }

    public void setSet(HashSet<String> set) {
        this.set = set;
    }

    public NominalValuesChooserPanel(HashSet<String> set) {
        this.set = set;
        amount = set.size();
        myInitComponents();
    }

    private void myInitComponents() {
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        ParallelGroup pg1;
        SequentialGroup sg1, sg2;

        /***** Horizontal *****/
        pg1 = layout.createParallelGroup(Alignment.LEADING);
        checkboxes = new JCheckBox[amount];
        Iterator iter = set.iterator();

        for (int i = 0; i < amount; i++) {
            checkboxes[i] = new JCheckBox((String) iter.next());
            pg1.addComponent(
                    checkboxes[i],
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE
                );
        }

        sg1 = layout.createSequentialGroup();
        sg1.addContainerGap()
           .addGroup(pg1)
           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sg1)
                );

        /***** Vertical *****/

        sg2 = layout.createSequentialGroup();
        sg2.addContainerGap();
        for (int i = 0; i < amount - 1; i++) {
            sg2.addComponent(
                    checkboxes[i],
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE
                );
            sg2.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        sg2.addComponent(checkboxes[amount - 1],
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE
            );
        sg2.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(sg2));
    }

    public HashSet<String> getSelectedValues() {
        HashSet<String> result = new HashSet<String>();
        for (JCheckBox jcb : checkboxes)
            if (jcb.isSelected())
                result.add(jcb.getText());
        return result;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
