/*
 * NominalValueInput.java
 *
 * Created on 2009-06-20, 20:39:01
 */

package apw.augmentedLearning.gui;

import java.util.HashSet;
import java.util.Iterator;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Nitric
 */
public class NominalValueInput extends ValueInputPanel {

    private String[] possibleValues;

    public NominalValueInput(String attName, HashSet<String> set) {
        System.out.println("attributeName = " + attName);
        int length = set.size();
        possibleValues = new String[length + 1];
        Iterator<String> iter = set.iterator();
        for (int i = 0; i < length; i++)
            possibleValues[i] = iter.next();
        possibleValues[length] = "?";
        initComponents();
        jl_attName.setText(attName);
        ComboBoxModel cbm = new DefaultComboBoxModel(possibleValues);
        jcb_value.setModel(cbm);
        setVisible(true);
    }

    /** Creates new form NominalValueInput */
    public NominalValueInput() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_attName = new javax.swing.JLabel();
        jcb_value = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(396, 42));

        jl_attName.setText("Nazwa atrybutu:");

        jcb_value.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_attName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_value, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jl_attName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_value, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcb_value;
    private javax.swing.JLabel jl_attName;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        String result = (String) jcb_value.getSelectedItem();
        return result.equals("?") ? null : result;
    }
}
