/*
 * PreviewOfSample.java
 *
 * Created on 2009-06-18, 00:32:26
 */

package apw.augmentedLearning.gui;

import apw.augmentedLearning.logic.DataFile;
import java.util.ArrayList;
import java.util.HashSet;

/**
 *
 * @author Nitric
 */
public class PreviewOfSample extends javax.swing.JFrame {

    public PreviewOfSample() {
        initComponents();
        jta.setEditable(false);
    }

    public PreviewOfSample(DataFile dataFile, HashSet<Integer>samples) {
        final StringBuilder sb = new StringBuilder();
        for (int currentSample : samples) {
            sb.append("Numer linijki pliku z danymi: " + (currentSample + 1) + "\n");
            Object[] sample = dataFile.getRawObjects()[currentSample];
            ArrayList<String> names = dataFile.getAttributesNames();
            for (int i = 0; i < dataFile.getAttributesCount(); i++) {
                sb.append(names.get(i) + " = " + sample[i] + "\n");
            }
            sb.append("------------------------------ \n");
        }
        initComponents();
        jta.setEditable(false);
        jta.setText(sb.toString());
        setVisible(true);
    }

    public PreviewOfSample(String s) {
        this();
        jta.setText(s);
        setVisible(true);
    }

    public void setText(String s) {
        jta.setText(s);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta.setColumns(20);
        jta.setRows(5);
        jsp.setViewportView(jta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTextArea jta;
    // End of variables declaration//GEN-END:variables

}
