/*
 * SampleInputPanel.java
 *
 * Created on 2009-06-20, 21:00:06
 */

package apw.augmentedLearning.gui;

import apw.augmentedLearning.logic.DataFile;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;

/**
 *
 * @author Nitric
 */
public class SampleInputPanel extends javax.swing.JPanel {

    private DataFile dataFile;
    private ValueInputPanel[] panels;
    private int amount = 3;

    /** Creates new form SampleInputPanel */
    public SampleInputPanel() {
        initComponents();
    }

    public SampleInputPanel(DataFile dataFile) {
        this.dataFile = dataFile;
        amount = dataFile.getAttributesCount();
        initPanels();
    }

    public Object getValue(int i) throws NumberFormatException {
        return panels[i].getValue();
    }

    private void initPanels() {
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        ParallelGroup pg1;
        SequentialGroup sg1, sg2;
        Vector<Integer> nominals = null;
        ArrayList<String> names = null;

        if (dataFile != null) {
            nominals = dataFile.getNominals();
            names = dataFile.getAttributesNames();
        }

        /***** Horizontal *****/
        pg1 = layout.createParallelGroup(Alignment.LEADING);
        panels = new ValueInputPanel[amount - 1];
        int panelCounter = 0;

        for (int i = 0; i < amount; i++) {
            if (i == dataFile.getClassAttributeIndex())
                continue;
            if (dataFile != null) {
                if (nominals.contains(i))
                    panels[panelCounter] =
                            new NominalValueInput(names.get(i), dataFile.getNominalValuesOfAttribute(i));
                else
                    panels[panelCounter] = new NumberValueInput(names.get(i));
            }
            else
                panels[panelCounter] = new NumberValueInput("Attrybut " + i); // dummy, in fact this should never happen in program
            pg1.addComponent(
                    panels[panelCounter++],
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE
                );
        }

        sg1 = layout.createSequentialGroup();
        sg1.addContainerGap()
           .addGroup(pg1)
           .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sg1)
                );
        
        /***** Vertical *****/

        sg2 = layout.createSequentialGroup();
        sg2.addContainerGap();
        for (int i = 0; i < amount - 2; i++) {
            sg2.addComponent(
                    panels[i],
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE
                );
            sg2.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        sg2.addComponent(panels[amount - 2],
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE
            );
        sg2.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(sg2));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nominalValueInput1 = new apw.augmentedLearning.gui.NominalValueInput();
        numberValueInput1 = new apw.augmentedLearning.gui.NumberValueInput();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nominalValueInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberValueInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nominalValueInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberValueInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apw.augmentedLearning.gui.NominalValueInput nominalValueInput1;
    private apw.augmentedLearning.gui.NumberValueInput numberValueInput1;
    // End of variables declaration//GEN-END:variables

}
